name: Refresh Sample SVG
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/**"
  schedule:
    - cron: "* */2 * * *"

jobs:
  execution:
    name: Deploying SVG to repository
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Fetch API Endpoint File
      id: api
      run: |
        mkdir -p docs
        curl -X GET "https://minicraft-plus-poeditor-stats-bencheung0422.vercel.app/api?api_token=${{ secrets.POEDITOR_API_TOKEN }}&id=${{ secrets.POEDITOR_PROJECT_ID }}" -o "docs/poeditor_stats.svg"
    
    - name: Save API Endpoint File & Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: Refresh & Update POEditor Stats SVG
        push: origin vercel-build --set-upstream --force
